// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjbhjhebsgetnwrafffo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqYmhqaGVic2dldG53cmFmZmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDEyMjMsImV4cCI6MjA1NjA3NzIyM30.-fRLR_1WXPRZfmnHIvTXo58Aw4PtjN6bR5v5KdLAmGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);